server{
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        welcome welcome.html welcome.htm;
        try_files $uri $uri/ /welcome.html =404;
    }
    
    include etc/nginx/extra-conf.d/*.conf;
}